name: CI

on:
  # Триггер при каждом коммите и pull request для ветки main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Возможность запуска вручную
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - uses: actions/checkout@v4

    # Шаг 2: Установка Python (например, для тестирования на Python)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Можно изменить на версию, которая вам нужна

    # Шаг 3: Установка зависимостей (например, если используется requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Зависимости проекта

    # Шаг 4: Запуск тестов
    - name: Run tests
      run: |
        pytest  # Здесь предполагается, что тесты можно запустить через pytest

    # Дополнительно: можете добавить покрытие тестов
    - name: Generate coverage report
      run: |
        pip install coverage
        coverage run -m pytest
        coverage report
